### 스펙 생성
POST http://localhost:8000/spec
Content-Type: application/json

{
  "url": "http://localhost:8080/limit",
  "path": {
    "value": "",
    "pathVariable": []
  },
  "method": "GET",
  "header": [
    {
      "key": "Content-Type",
      "value": "application/json"
    },
    {
      "key": "Authorization",
      "value": "Bearer token"
    }
  ],
  "queryParam": [],
  "payload": {
    "properties": []
  },
  "name": "데모 호출"
}

### 상품 스펙 생성
POST http://localhost:8000/spec
Content-Type: application/json

{
  "url": "http://localhost:8081",
  "path": {
    "value": "/sellers/{sellerId}/products",
    "pathVariable": [
      {
        "type": "LONG",
        "name": "sellerId",
        "domain": {
          "type": "RANGE",
          "from": 20,
          "to": 100
        }
      }
    ]
  },
  "method": "POST",
  "header": [
    {
      "key": "Content-Type",
      "value": "application/json"
    }
  ],
  "queryParam": [],
  "payload": {
    "properties": [
      {
        "type": "STRING",
        "name": "representativeImage",
        "domain": {
          "type": "IMAGE"
        }
      },
      {
        "type": "STRING",
        "name": "name"
      },
      {
        "type": "LONG",
        "name": "price",
        "domain": {
          "type": "RANGE",
          "from": 1000,
          "to": 100000
        }
      },
      {
        "type": "OBJECT",
        "name": "stock",
        "properties": [
          {
            "type": "STRING",
            "name": "ids",
            "domain": {
              "multiple": true
            }
          },
          {
            "type": "LONG",
            "name": "quantity",
            "domain": {
              "type": "RANGE",
              "from": 1000,
              "to": 100000
            }
          }
        ]
      },
      {
        "type": "OBJECT",
        "name": "productDetail",
        "properties": [
          {
            "type": "STRING",
            "name": "qualityAssuranceStandard"
          },
          {
            "type": "STRING",
            "name": "notice"
          }
        ]
      },
      {
        "type": "STRING",
        "name": "category",
        "domain": {
          "type": "ENUM",
          "values": [
            "ELECTRONICS",
            "CLOTHING",
            "FOOD",
            "FURNITURE",
            "SPORTS",
            "BOOKS",
            "BEAUTY",
            "HOME_GOODS",
            "PET_SUPPLIES",
            "OTHERS"
          ]
        }
      },
      {
        "type": "STRING",
        "name": "tags",
        "domain": {
          "multiple": true
        }
      }
    ]
  },
  "name": "셀러 상품 등록"
}


### 회원 등록 스펙 생성 6e0419f
POST http://localhost:8000/spec
Content-Type: application/json

{
  "url": "http://localhost:8080",
  "path": {
    "value": "/v1/members",
    "pathVariable": []
  },
  "method": "POST",
  "header": [
    {
      "key": "Content-Type",
      "value": "application/json"
    }
  ],
  "queryParam": [],
  "payload": {
    "properties": [
      {
        "type": "STRING",
        "name": "oauthId"
      },
      {
        "type": "STRING",
        "name": "name"
      }
    ]
  },
  "name": "회원 등록"
}


### 회원 정보 조회 스펙 생성 282b7d4
POST http://localhost:8000/spec
Content-Type: application/json

{
  "url": "http://localhost:8080",
  "path": {
    "value": "/v1/members",
    "pathVariable": []
  },
  "method": "GET",
  "header": [
    {
      "key": "Content-Type",
      "value": "application/json"
    }
  ],
  "queryParam": [
    {
      "key": "token",
      "value": "{token}",
      "variable": {
        "type": "STRING",
        "name": "token"
      }
    }
  ],
  "payload": {
    "properties": []
  },
  "name": "회원 조회"
}

### 모든 스펙 조회
GET http://localhost:8000/spec

### payload 실행
GET http://localhost:8000/spec/1a962de

### 영화 등록 스펙 생성 e15055b
POST http://localhost:8000/spec
Content-Type: application/json

{
  "url": "http://localhost:8080",
  "path": {
    "value": "/v1/movies",
    "pathVariable": []
  },
  "method": "POST",
  "header": [
    {
      "key": "Content-Type",
      "value": "application/json"
    }
  ],
  "queryParam": [],
  "payload": {
    "properties": [
      {
        "type": "STRING",
        "name": "movieName"
      },
      {
        "type": "STRING",
        "name": "poster",
        "domain": {
          "type": "IMAGE"
        }
      },
      {
        "type": "STRING",
        "name": "director"
      },
      {
        "type": "STRING",
        "name": "actors",
        "domain": {
          "multiple": true
        }
      },
      {
        "type": "OBJECT",
        "name": "detail",
        "properties": [
          {
            "type": "DATE",
            "name": "open",
            "domain": {
              "type": "RANGE",
              "start": "1997-01-01T00:00:00",
              "end": "2025-12-31T00:00:00"
            }
          },
          {
            "type": "STRING",
            "name": "categories",
            "domain": {
              "type": "ENUM",
              "multiple": true,
              "values": [
                "ACTION",
                "ADVENTURE",
                "ANIMATION",
                "BIOGRAPHY",
                "COMEDY",
                "CRIME",
                "DOCUMENTARY",
                "DRAMA",
                "FAMILY",
                "FANTASY",
                "HISTORY",
                "HORROR",
                "MUSIC",
                "MUSICAL",
                "MYSTERY",
                "ROMANCE",
                "SCI_FI",
                "SPORT",
                "THRILLER",
                "WAR",
                "WESTERN",
                "ETC"
              ]
            }
          },
          {
            "type": "STRING",
            "name": "country",
            "domain": {
              "type": "ENUM",
              "values": [
                "USA",
                "KOR",
                "JPN",
                "CHN",
                "GBR",
                "FRA",
                "ETC"
              ]
            }
          },
          {
            "type": "LONG",
            "name": "runningTime",
            "domain": {
              "type": "RANGE",
              "from": 60,
              "to": 200
            }
          },
          {
            "type": "STRING",
            "name": "distributor"
          }
        ]
      }
    ]
  },
  "name": "영화 등록"
}
